### ISSUE TITLE
CPU maxed at 99 percent usage on a single core

### ISSUE THREAD

**Issue by z0mbieslayer** [de-bil/TINE#5]
Not sure if this is known or not, but I just built it today using WSL and when I run it, it pegs one core of my CPU to 99 and TOS is basically unusable.

**Comment by z0mbieslayer** [comment]
Nevermind, seems it's just that way on startup for a bit. Probably for obvious reasons.

**Comment by de-bil** [comment]
Why were you using WSL? From what I remember I have written clearly that you should use MSys2 for building TINE on Windows natively. WSL is not recommended for performance reasons.

The reason it does that on startup is due to ACInit() parsing HolyC files and loading them into the autocomplete list. This usually barely takes a split second even on very old hardware, but due to the usage of WSL as you have mentioned, it takes much more time (I can think of many reasons as to why it's so slow, but I will not elaborate as they are irrelevant to TINE itself). If you really want to use WSL for whatever reason, you can change the `ACInit("*.HC;*.HH");` in line 64 of T/FULL_PACKAGE.HC to `ACInit("KERNEL*.HH");` and recompile the kernel with `./tine -ctT BuildHCRT.HC`. You'll get a smaller autocomplete list but it won't be significant and it'll improve startup times by a lot.

My point is to use MSys2 as advised strongly in the readme.

**Comment by de-bil** [comment]
I don't understand what errors you have run into while building it on MSys2. I have just tested it and it builds perfectly.
I highly suspect that you have used a shell that I have not specified in the readme, such as UCRT64. Please try again using the "MSYS2 MINGW64" shell as *explicitly stated* in the readme and screenshot/report back any errors you got while building.

![image](https://github.com/de-bil/TINE/assets/137516603/3d5a335f-0e3a-47c1-94c4-c009a4abf8c5)

**Comment by z0mbieslayer** [comment]
You're right, I was using a different shell. Guess I didn't think it would make much of a difference. Will try with msys2 when I get home, I have no doubt everything should go correctly.
